using Iuliia.Dto;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Generic;
using System.Linq;
using System.Security;
using System.Text;
using System.Text.Json;

namespace Iuliia.SourceGenerator
{
    [Generator]
    public class SchemaGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var jsonFiles = context.AdditionalTextsProvider
                .Where(file => file.Path.EndsWith(".json"));

            var allFilesCollected = jsonFiles.Collect();

            context.RegisterSourceOutput(allFilesCollected, (spc, files) =>
            {
                if (files.IsEmpty) return;

                var codeBuilder = new StringBuilder();

                codeBuilder.AppendLine("// <auto-generated/>");
                codeBuilder.AppendLine("using System;");
                codeBuilder.AppendLine("using System.Collections.Generic;");
                codeBuilder.AppendLine();
                codeBuilder.AppendLine("namespace Iuliia;");
                codeBuilder.AppendLine();
                codeBuilder.AppendLine("public static class Schemas");
                codeBuilder.AppendLine("{");

                foreach (var file in files)
                {
                    var text = file.GetText()?.ToString();
                    if (text == null)
                        continue;

                    var scheme = JsonSerializer.Deserialize<SchemeDto>(text);
                    if (scheme == null)
                        continue;

                    var samples = string.Join(", ", scheme.Samples.Select(x => $"new Sample({Print(x[0])}, {Print(x[1])})"));
                    codeBuilder.AppendLine($$"""
                    /// <summary>
                    /// {{EscapeXmlDoc(scheme.Description)}}
                    /// </summary>
                    public static Scheme {{GetPropertyName(scheme.Name)}} { get; } = new Scheme(
                        {{Print(scheme.Name)}},
                        {{PrintDictionary(scheme.Mapping.ToDictionary(x => x.Key[0], x => x.Value))}},
                        {{PrintDictionary(scheme.PreviousMapping)}},
                        {{PrintDictionary(scheme.NextMapping)}},
                        {{PrintDictionary(scheme.EndingMapping)}},
                        new Sample[] { {{samples}} });
                """);
                    codeBuilder.AppendLine();
                }

                codeBuilder.AppendLine("}");
                
                spc.AddSource("Schemas.g.cs", SourceText.From(codeBuilder.ToString(), Encoding.UTF8));
            });
        }

        private static string PrintDictionary<TKey, TValue>(IDictionary<TKey, TValue>? dictionary)
        {
            if (dictionary == null)
                return "null";

            var pairs = string.Join(", ", dictionary.Select(x => $"[{Print(x.Key)}] = {Print(x.Value)}"));
            return $"new Dictionary<{typeof(TKey)},{typeof(TValue)}> {{ { pairs } }}";
        }

        private static string Print(object? value) => value switch
        {
            null => "null",
            char c => SyntaxFactory.LiteralExpression(SyntaxKind.CharacterLiteralExpression, SyntaxFactory.Literal(c)).ToFullString(),
            string s => SyntaxFactory.LiteralExpression(SyntaxKind.StringLiteralExpression, SyntaxFactory.Literal(s)).ToFullString(),
            _ => value.ToString()
        };

        private static string EscapeXmlDoc(string value) => SecurityElement.Escape(value) ?? "";

        private static string GetPropertyName(string schemeName)
        {
            var acronymParts = new HashSet<string>
            {
                "ala", "bgn", "pcgn", "bs", "gost", "icao", "doc", "iso", "mvd", "fr", "ungegn", "lc"
            };

            var parts = schemeName.Split('_');
            var convertedParts = parts
                .Select(part => acronymParts.Contains(part) || part.All(char.IsDigit)
                    ? part.ToUpperInvariant()
                    : char.ToUpperInvariant(part[0]) + part.Substring(1))
                .ToArray();

            return convertedParts.Any(part => part == part.ToUpperInvariant())
                ? string.Join("_", convertedParts)
                : string.Join("", convertedParts);
        }
    }
}
